# Generated by Django 4.2.2 on 2023-06-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_otp',
            field=models.IntegerField(max_length=50),
        ),
    ]
