# Generated by Django 4.2.2 on 2023-06-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_otp',
            field=models.IntegerField(),
        ),
    ]
